trigger: none

pool:
  vmImage: ubuntu-latest


stages:
  - stage: "Scan"
    displayName: "Scan Images"
    jobs:
      -  job: "Trivy_Scan1"
         displayName: "Trivy Scan using Container Image"
         steps:
          - task: DockerInstaller@0
            displayName: "Docker Installation"
            inputs:
              dockerVersion: '17.09.0-ce'

          - task: CmdLine@2
            displayName: "Trivy Scan using Container Image"
            inputs:
              script: |
                imagename=$(awk 'NR==1 {print $2}' Dockerfile)      
                docker run --rm -v $(pwd)/.trivyignore:/work/.trivyignore -w /work -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy -q image --exit-code 1 --severity CRITICAL --light $imagename

      - job: "Trivy_Scan2"
        dependsOn: 'Trivy_Scan1'
        displayName: "Trivy Scan Using Trivy Installation"
        steps:
          - task: CmdLine@2
            displayName: "Trivy Installation"
            inputs:
              script: |
                wget https://github.com/aquasecurity/trivy/releases/download/v0.43.1/trivy_0.43.1_Linux-64bit.deb
                
                sudo dpkg -i trivy_0.43.1_Linux-64bit.deb
          
          - task: CmdLine@2
            displayName: "Trivy Scan"
            inputs:
              script: |
                imagename=$(awk 'NR==1 {print $2}' Dockerfile)
                
                trivy -q image --exit-code 0 --severity CRITICAL --light $imagename
              workingDirectory: '$(System.DefaultWorkingDirectory)'


      - job: "Clair_Scan"
        dependsOn: 'Trivy_Scan2'
        displayName: "Clair Scan Using Clair Installation"
        steps:

          - task: DockerInstaller@0
            displayName: "Docker Installation"
            inputs:
              dockerVersion: '17.09.0-ce'

          - task: CmdLine@2
            displayName: 'Image Scan using Clair'
            inputs:
              script: |
                imagename=$(awk 'NR==1 {print $2}' Dockerfile)
                
                sudo curl -L https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64 -o /usr/bin/clair-scanner
                
                sudo chmod +x /usr/bin/clair-scanner
                
                
                docker run -p 5432:5432 -d --name db arminc/clair-db:latest
                
                docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:latest
                
                docker pull $imagename
                
                clair-scanner -w whitelist.yaml --ip 172.17.0.1 $imagename
              workingDirectory: '$(System.DefaultWorkingDirectory)'