trigger: 'none'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "Scan"
    displayName: "Scan"
    jobs: 
     - job: "MendBolt"
       displayName: "MendBolt Scan"
       steps:
         - task: WhiteSource@21
           inputs:
             cwd: '$(System.DefaultWorkingDirectory)'
             projectName: 'SpringBoot-NodeJs'