trigger: 'none'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "Build"
    displayName: "Build"
    jobs:
      -  job: "BuildApp"
         displayName: "Build App"
         steps:

           - task: SonarCloudPrepare@1
             displayName: "SonarCloud Analysis Preparation"
             inputs:
               SonarCloud: 'SonarSconn'
               organization: 'mydemoado1'
               scannerMode: 'Other'
               extraProperties: |
                 # Additional properties that will be passed to the scanner, 
                 # Put one key=value per line, example:
                 # sonar.exclusions=**/*.bin
                 
                 sonar.projectKey=MyDemoADO_SpringBoot-NodeJs
                 sonar.projectName=SpringBoot-NodeJs
                 sonar.scanner.metadataFilePath=$(Agent.TempDirectory)/sonar/$(Build.BuildNumber)/test/report-task.txt
                
              

           - task: Maven@4
             displayName: "Maven Test with Junit and Code Coverage with JaCoCo"
             inputs:
               mavenPomFile: 'pom.xml'
               goals: 'clean test'
               publishJUnitResults: false
               codeCoverageToolOption: 'JaCoCo'
               javaHomeOption: 'JDKVersion'
               mavenVersionOption: 'Default'
               mavenAuthenticateFeed: false
               effectivePomSkip: false
               sonarQubeRunAnalysis: true
               sqMavenPluginVersionChoice: 'latest'

           
           - task: PublishTestResults@2
             displayName: "Publish Unit Test Results"
             inputs:
               testResultsFormat: 'JUnit'
               testResultsFiles: '**/surefire-reports/TEST-*.xml'
               failTaskOnFailedTests: true


           - task: SonarCloudPublish@1
             displayName: "SonarCloud Quality Gate Result"
             inputs:
               pollingTimeoutSec: '300'

           - task: sonarcloud-buildbreaker@2
             displayName: "Build Breaker if QG fails"
             inputs:
               SonarCloud: 'SonarSconn'
               organization: 'mydemoado1'
           
           - task: Maven@4
             displayName: "Package it in its distributable format"
             inputs:
               mavenPomFile: 'pom.xml'
               goals: 'clean package'
               publishJUnitResults: false
               javaHomeOption: 'JDKVersion'
               mavenVersionOption: 'Default'
               mavenAuthenticateFeed: false
               effectivePomSkip: false
               sonarQubeRunAnalysis: false

           - task: CopyFiles@2
             inputs:
               SourceFolder: '$(System.DefaultWorkingDirectory)'
               Contents: '**/numeric-0.0.1.jar'
               TargetFolder: '$(Build.ArtifactStagingDirectory)'

           - task: PublishBuildArtifacts@1
             inputs:
               PathtoPublish: '$(Build.ArtifactStagingDirectory)/target'
               ArtifactName: 'drop'
               publishLocation: 'Container'

  - stage: "Deployment"
    dependsOn: "Build"
    displayName: "Deployment"
    jobs:
      - job: "Test_Deployment"
        displayName: "Deployment to Test Env"
        steps:
          - task: CmdLine@2
            inputs:
              script: 'echo Test Env'