pool:
  vmImage: ubuntu-latest

resources:
  webhooks:
    - webhook: Sonarwebhook
      connection: SonarIncomingSconn
      filters:
        - path: project      
          value: 'MyDemoADO_SpringBoot-NodeJs'

steps:
  - checkout: none
  - task: PowerShell@2
    inputs:
     targetType: 'inline'
     script: 'Write-Host ${{ parameters.Sonarwebhook.status}}'