trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'MavenPackageDeploy'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    options: '-DaltDeploymentRepository=MavenPackageDeploy::default::https://pkgs.dev.azure.com/MyDemoADO/SpringBoot-NodeJs/_packaging/MavenPackageDeploy/maven/v1'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false