trigger: 'none'

pool:
  vmImage: ubuntu-latest


stages:
  - stage: "Build"
    displayName: "Build App"
    jobs:
      -  job: "Build"
         displayName: "Build Webapp"
         steps:

           - task: SonarCloudPrepare@1
             inputs:
               SonarCloud: 'SonarSconn'
               organization: 'mydemoado1'
               scannerMode: 'Other'
               extraProperties: |
                 # Additional properties that will be passed to the scanner, 
                 # Put one key=value per line, example:
                 # sonar.exclusions=**/*.bin
                 
                 sonar.projectKey=MyDemoADO_SpringBoot-NodeJs
                 sonar.projectName=SpringBoot-NodeJs
                 sonar.scanner.metadataFilePath=$(Agent.TempDirectory)/sonar/$(Build.BuildNumber)/test/report-task.txt
                
              

           - task: Maven@4
             inputs:
               mavenPomFile: 'pom.xml'
               goals: 'test'
               publishJUnitResults: false
               codeCoverageToolOption: 'JaCoCo'
               javaHomeOption: 'JDKVersion'
               mavenVersionOption: 'Default'
               mavenAuthenticateFeed: false
               effectivePomSkip: false
               sonarQubeRunAnalysis: true
               sqMavenPluginVersionChoice: 'latest'

           
           - task: PublishTestResults@2
             inputs:
               testResultsFormat: 'JUnit'
               testResultsFiles: '**/surefire-reports/TEST-*.xml'
               failTaskOnFailedTests: true


           - task: SonarCloudPublish@1
             inputs:
               pollingTimeoutSec: '300'

           - task: sonarcloud-buildbreaker@2
             inputs:
               SonarCloud: 'SonarSconn'
               organization: 'mydemoado1'
