trigger: none

pool:
  vmImage: ubuntu-latest

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: CmdLine@2
  inputs:
    script: |
      imagename=$(awk 'NR==1 {print $2}' Dockerfile)      
      
      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:0.17.2 --severity CRITICAL --light $imagename

