trigger: none

pool:
  vmImage: ubuntu-latest


steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.0'
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.12.0'
  
  - task: gitversion/execute@0
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)'
  
  - task: CmdLine@2
    inputs:
      script: 'echo current version is $(GitVersion.SemVer)'