trigger: 'none'

pool:
  vmImage: ubuntu-latest


stages:
  - stage: "Build"
    displayName: "Build App"
    jobs:
      -  job: "Build"
         displayName: "Build Webapp"
         steps:
           - task: Maven@4
             inputs:
               mavenPomFile: 'pom.xml'
               goals: 'test'
               publishJUnitResults: true
               testResultsFiles: '**/surefire-reports/TEST-*.xml'
               codeCoverageToolOption: 'JaCoCo'
               codeCoverageFailIfEmpty: true
               javaHomeOption: 'JDKVersion'
               mavenVersionOption: 'Default'
               mavenAuthenticateFeed: false
               effectivePomSkip: false
               sonarQubeRunAnalysis: false
            
           - task: PublishCodeCoverageResults@2
             inputs:
               summaryFileLocation: '(System.DefaultWorkingDirectory)/surefire-reports/TEST-*.xml'

           - task: BuildQualityChecks@9
             inputs:
                checkCoverage: true
                coverageFailOption: 'fixed'
                coverageType: 'lines'
                coverageThreshold: '85'