trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: gitversion/setup@0
  inputs:
    preferLatestVersion: true

- task: gitversion/execute@0

- script: echo current version is $(GitVersion.SemVer)