trigger: 'none'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "Build"
    displayName: "Build"
    jobs:
      -  job: "BuildApp"
         displayName: "Build App"
         steps:

           - task: SonarCloudPrepare@1
             displayName: "SonarCloud Analysis Preparation"
             inputs:
               SonarCloud: 'SonarSconn'
               organization: 'mydemoado1'
               scannerMode: 'Other'
               extraProperties: |
                 # Additional properties that will be passed to the scanner, 
                 # Put one key=value per line, example:
                 # sonar.exclusions=**/*.bin
                 
                 sonar.projectKey=MyDemoADO_SpringBoot-NodeJs
                 sonar.projectName=SpringBoot-NodeJs
                 sonar.scanner.metadataFilePath=$(Agent.TempDirectory)/sonar/$(Build.BuildNumber)/test/report-task.txt
                
              

           - task: Maven@4
             displayName: "Maven Test with Junit and Code Coverage with JaCoCo"
             inputs:
               mavenPomFile: 'pom.xml'
               goals: 'clean test'
               publishJUnitResults: false
               codeCoverageToolOption: 'JaCoCo'
               javaHomeOption: 'JDKVersion'
               mavenVersionOption: 'Default'
               mavenAuthenticateFeed: false
               effectivePomSkip: false
               sonarQubeRunAnalysis: true
               sqMavenPluginVersionChoice: 'latest'

           - task: CopyFiles@2
             inputs:
               SourceFolder: '$(System.DefaultWorkingDirectory)'
               Contents: '**/surefire-reports/TEST-*.xml'
               TargetFolder: '$(Build.ArtifactStagingDirectory)' 


           - task: PowerShell@2
             displayName: "Check Test Pass Percentage"
             inputs:
               targetType: 'inline'
               script: |
                 [xml]$xml= Get-Content $(build.artifactstagingdirectory)\target\surefire-reports\TEST-com.devsecops.NumericApplicationTests.xml
                 $failures= $xml.testsuite.failures
                 $tests= $xml.testsuite.tests
                 $passpercent=[Math]::Abs(($failures/$tests - 1)*100)
                 
                 $passpercent
                 
                 If($passpercent -lt 90)
                 {
                 Write-host "Threshold Breached.Exit 1"
                 EXIT 1
                 }
                 

           - task: BuildQualityChecks@9
             displayName: "Check Code Coverage Percentage"
             inputs:
               checkCoverage: true
               coverageFailOption: 'fixed'
               coverageType: 'lines'
               coverageThreshold: '60'


           - task: PublishTestResults@2
             displayName: "Publish Unit Test Results"
             inputs:
               testResultsFormat: 'JUnit'
               testResultsFiles: '**/surefire-reports/TEST-*.xml'
               failTaskOnFailedTests: true


           - task: SonarCloudPublish@1
             displayName: "SonarCloud Quality Gate Result"
             inputs:
               pollingTimeoutSec: '300'

           - task: sonarcloud-buildbreaker@2
             displayName: "Build Breaker if QG fails"
             inputs:
               SonarCloud: 'SonarSconn'
               organization: 'mydemoado1'
           
           - task: Maven@4
             displayName: "Package it in its distributable format"
             inputs:
               mavenPomFile: 'pom.xml'
               goals: 'clean package'
               options: '-DskipTests=true'
               publishJUnitResults: false
               javaHomeOption: 'JDKVersion'
               mavenVersionOption: 'Default'
               mavenAuthenticateFeed: false
               effectivePomSkip: false
               sonarQubeRunAnalysis: false

           - task: CopyFiles@2
             inputs:
               SourceFolder: '$(System.DefaultWorkingDirectory)'
               Contents: '**/numeric-0.0.1.jar'
               TargetFolder: '$(Build.ArtifactStagingDirectory)'

           - task: PublishBuildArtifacts@1
             inputs:
               PathtoPublish: '$(Build.ArtifactStagingDirectory)'
               ArtifactName: 'drop'
               publishLocation: 'Container'

           - task: UniversalPackages@0
             inputs:
               command: 'publish'
               publishDirectory: '$(Build.ArtifactStagingDirectory)/target/'
               feedsToUsePublish: 'internal'
               vstsFeedPublish: '545dde5f-5bea-4cde-8e74-74e78a4710b3/337d99bd-18b3-4cd6-984f-b3c7f5ef2812'
               vstsFeedPackagePublish: 'numeric'
               versionOption: 'patch'


  - stage: "Deployment"
    dependsOn: "Build"
    displayName: "Deployment"
    jobs:
      

      - job: "Approval"
        pool: server

        steps:
          
          - task: ManualValidation@0
            timeoutInMinutes: 1
            displayName: "Deployment Validation"
            inputs:
              notifyUsers: 'aniket.p.deshmukh@gmail.com'
              instructions: 'Please validate the build $(Build.BuildId) configuration and resume'


      - job: "Test_Deployment"
        displayName: "Deployment to Test Env"
        dependsOn: "Approval"
        steps:
          - task: CmdLine@2
            inputs:
              script: 'echo Test Env'