trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.3.x'

  - task: gitversion/execute@0
  
  - script: echo current version is $(GitVersion.SemVer)