trigger:
- feature*

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $tags = git tag
      $tags

- task: CmdLine@2
  inputs:
    script: 'echo  git tag value is $(tags)'