trigger:
- feature*

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $tags = git tag
      $tags


- task: UseDotNet@2
  inputs:
      packageType: 'runtime'
      version: '3.x'
      includePreviewVersions: true

- task: UseDotNet@2
  inputs:
      packageType: 'runtime'
      version: '6.x'
      includePreviewVersions: true


- task: gitversion/setup@0
  inputs:
      versionSpec: '5.12.0'
  
- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: 'GitVersion.yml'
  
- task: CmdLine@2
  inputs:
      script: 'echo current version is $(GitVersion.SemVer)'