trigger: 'none'

pool:
  name: Default
  demands:
   - agent.name -equals LAPTOP-FHLQ0U7M

stages:
  - stage: "Scan"
    displayName: "Scan"
    jobs: 
     - job: "MendBolt"
       displayName: "MendBolt Scan"
       steps:
         - task: WhiteSource@21
           inputs:
             cwd: '$(System.DefaultWorkingDirectory)'
             projectName: 'SpringBoot-NodeJs'
             

         - task: dependency-check-build-task@6
           inputs:
             projectName: 'SpringBootwithNodeJS'
             scanPath: '$(System.DefaultWorkingDirectory)'
             format: 'ALL'
             failOnCVSS: '9.9'

         - task: PublishTestResults@2
           inputs:
             testResultsFormat: 'JUnit'
             testResultsFiles: 'dependency*junit*.xml'
             searchFolder: 'C:\Aniket\K8-DevSecOps\SelfHosted\_work\1\TestResults\dependency-check\'
             testRunTitle: 'Dependency Check'