trigger: 'none'

pool:
  vmImage: ubuntu-latest


stages:
  - stage: "Build"
    displayName: "Build App"
    jobs:
      -  job: "Build"
         displayName: "Build Webapp"
         steps:
           - task: Maven@4
             inputs:
               mavenPomFile: 'pom.xml'
               goals: 'test'
               publishJUnitResults: false
               codeCoverageToolOption: 'JaCoCo'
               codeCoverageFailIfEmpty: true
               javaHomeOption: 'JDKVersion'
               mavenVersionOption: 'Default'
               mavenAuthenticateFeed: false
               effectivePomSkip: false
               sonarQubeRunAnalysis: false

           - task: PublishTestResults@2
             inputs:
               testResultsFormat: 'JUnit'
               testResultsFiles: '**/surefire-reports/TEST-*.xml'
               failTaskOnFailedTests: true
            
           
           - task: BuildQualityChecks@9
             inputs:
                checkCoverage: true
                coverageFailOption: 'fixed'
                coverageType: 'lines'
                coverageThreshold: '60'
           