trigger: 'none'

pool:
  vmImage: ubuntu-latest

resources:
  webhooks:
    - webhook: Sonarwebhook
      connection: SonarIncomingSconn

steps:
  - task: PowerShell@2
    inputs:
     targetType: 'inline'
     script: 'Write-Host ${{ parameters.Sonarwebhook.status}}'